In [15]:
import importlib

import wrds
import pandas as pd
import datetime
import numpy as np
import pickle
from time import time, sleep
import argparse as ap
import sys
import csv
from dateutil.relativedelta import relativedelta
from collections import OrderedDict

db = wrds.Connection()

Enter your WRDS username [dlflath23]:dflath19
Enter your password:········
WRDS recommends setting up a .pgpass file.
You can find more info here:
https://www.postgresql.org/docs/9.5/static/libpq-pgpass.html.
Loading library list...
Done

In [29]:
def previous_quarter(date_string):
    ref = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()
    if ref.month < 4:
        return datetime.date(ref.year - 1, 12, 31)
    elif ref.month < 7:
        return datetime.date(ref.year, 3, 31)
    elif ref.month < 10:
        return datetime.date(ref.year, 6, 30)
    return datetime.date(ref.year, 9, 30)

def top_n_mkt_cap_gvkeys(date_string,n,gvkeys):
    date1 = previous_quarter(date_string)
    date2 = previous_quarter(date1.strftime('%Y-%m-%d'))
    gvkeys_list = tuple(["'%s'"%str(i) for i in gvkeys])
    gvkeys_list = ",".join(gvkeys_list)
    q1 = ("select datadate, gvkey,cshoq,prccq,cshoq*prccq as market_cap, curcdq "
            "from compm.fundq "
           "where cshoq>0 and prccq>0 and curcdq='USD' and datadate > '%s' and datadate <= '%s' and gvkey in (%s) "
         "order by market_cap desc "
        "limit %i") % (date2,date1,gvkeys_list,n)
    df = db.raw_sql(q1)
    return list(df.gvkey.unique())

def gvkeys_for_filtered_security_type(date_string):
    year = date_string[0:4]
    date1 = previous_quarter(date_string)
    date2 = previous_quarter(date1.strftime('%Y-%m-%d'))
    q1 = ("select gvkey,cyear,tpci,exchg,datadate "
            "from compm.secm "
           "where datadate > '%s' and datadate <= '%s' and tpci in ('0','F') and exchg in (11,12,14,19) ")% (date2,date1)
    df = db.raw_sql(q1)
    return list(df.gvkey.unique())

def gvkeys_for_filtered_sectors(date_string,gvkeys):
    gvkeys_list = tuple(["'%s'"%str(i) for i in gvkeys])
    gvkeys_list = ",".join(gvkeys_list)
    q1 = ("select gvkey,gsector,loc "
            "from compm.company "
           "where gsector != '40' and gvkey in (%s) and loc='USA' ")% gvkeys_list
    df = db.raw_sql(q1)
    return list(df.gvkey.unique())

def get_latest_prices(date_string,gvkeys):
    gvkeys_list = tuple(["'%s'"%str(i) for i in gvkeys])
    gvkeys_list = ",".join(gvkeys_list)
    q1 = ("select datadate,gvkey,prccd,tpci "
            "from compm.secd "
           "where datadate = '%s' and gvkey in (%s) and tpci in ('0','F') ") % (date_string,gvkeys_list)
    df = db.raw_sql(q1)
    while True:
        if df.gvkey.nunique() == 0:
            date = datetime.datetime.strptime(date_string, "%Y-%m-%d") - datetime.timedelta(days=1)
            date_string = date.strftime('%Y-%m-%d')
            q1 = ("select datadate,gvkey,prccd,tpci "
            "from compm.secd "
           "where datadate = '%s' and gvkey in (%s) and tpci in ('0','F') ") % (date_string,gvkeys_list)
            df = db.raw_sql(q1)
        else:
            break
    return df

def get_cheapest_50_tics(date_string,gvkeys):
    date1 = previous_quarter(date_string)
    date2 = previous_quarter(date1.strftime('%Y-%m-%d'))
    date3 = date2 - relativedelta(years=4)
    gvkeys_list = tuple(["'%s'"%str(i) for i in gvkeys])
    gvkeys_list = ",".join(gvkeys_list)
    q1 = ("select datadate,gvkey,tic,cusip,oiadpq,cshoq,prccq,pstkq, dlcq, dlttq, cheq,niq,ceqq "
            "from compm.fundq "
           "where datadate <= '%s' and datadate > '%s' and gvkey in (%s) ") % (date2,date3,gvkeys_list)
    df = db.raw_sql(q1)
    df["date"] = pd.to_datetime(df['datadate'], format='%Y-%m-%d')
    df.sort_values(by=["date"])
    df = df.groupby('gvkey').ffill()
    df['oiadpq_ttm'] = df.groupby('gvkey')['oiadpq'].apply(lambda x: x.ffill().rolling(window=4).sum())
    df['roe'] = df['niq'] / df['ceqq']
    df['roe_3yr_avg'] = df.groupby('gvkey')['roe'].apply(lambda x: x.ffill().rolling(window=12).sum()/12)
    latest_prices = get_latest_prices(date_string,gvkeys)
    df = pd.merge(df, latest_prices, on = 'gvkey', how='left')
    df["market_cap"] = df["cshoq"] * df["prccd"]
    df["ent_value"] = df["market_cap"] + df["pstkq"] + df["dlcq"] + df["dlttq"] - df["cheq"]
    df["ev_ebit"] = (df["ent_value"] / df["oiadpq_ttm"])
    df["net_debt"] = df["dlcq"] + df["dlttq"] - df["cheq"]
    df["net_debt_ebit_ttm"] = df["net_debt"] / df['oiadpq_ttm']
    df = df.round({'market_cap': 2, 'ent_value': 2, 'ev_ebit' : 2, 'roe' : 4, 'roe_3yr_avg' : 4, 'net_debt_ebit_ttm' : 2})
    df = df.loc[df['ev_ebit'] > 0]
    df = df.sort_values(by=["roe_3yr_avg"],ascending=False)
    df = df.groupby('gvkey').apply(lambda g: g[g['date'] == g['date'].max()])
    df = df.loc[df['roe_3yr_avg'] >= 0.10]
    df = df.loc[df['net_debt_ebit_ttm'] <= 4.00]
    df = df.sort_values(by=["ev_ebit"])
    df = df.head(50)
    tics = [t.split('.')[0] for t in list(df.tic.unique())]
    
    return df.filter(items=['tic','date','niq','ceqq','roe','roe_3yr_avg','ev_ebit','net_debt_ebit_ttm'])
    #return df
    #return tics

def get_tics(date_string):
    gvkeys = gvkeys_for_filtered_security_type(date_string)
    sector_filtered = gvkeys_for_filtered_sectors(date_string,gvkeys)
    top_n_gvkeys = top_n_mkt_cap_gvkeys(date_string,1000,sector_filtered)
    d = get_cheapest_50_tics(date_string,top_n_gvkeys)
    return d

get_tics('2016-01-01')

                tic       date       niq       ceqq     roe  roe_3yr_avg  \
gvkey
165652 14408    WNR 2015-09-30   153.303   1318.467  0.1163       0.1085
012785 6339     PPC 2015-09-30   137.062   1239.616  0.1106       0.1145
004990 2113     GPS 2015-04-30   239.000   2879.000  0.0830       0.1018
001045 15       AAL 2015-09-30  1693.000   3762.000  0.4500       0.2556
010443 5059     TEN 2015-09-30    52.000    447.000  0.1163       0.1503
170297 14504    NTI 2015-09-30   103.500    497.300  0.2081       0.1597
009248 4595    ROST 2015-04-30   282.205   2333.499  0.1209       0.1112
165675 14439   VIAB 2015-09-30   884.000   3538.000  0.2499       0.1281
024856 9086    GILD 2015-09-30  4600.000  17414.000  0.2642       0.1648
165675 14440   VIAB 2015-09-30   884.000   3538.000  0.2499       0.1281
005234 2225      GT 2015-09-30   271.000   4143.000  0.0654       0.2710
014311 6931     PII 2015-03-31    88.563    862.278  0.1027       0.1351
032280 10708  STRZA 2015-09-30    60.200    229.400  0.2624       0.6659
       10709  STRZA 2015-09-30    60.200    229.400  0.2624       0.6659
175263 14840     WU 2015-09-30   232.300   1347.200  0.1724       0.1889
008606 4323     PBI 2015-09-30    89.282    141.507  0.6309       0.5199
012589 6307     HLS 2015-09-30    50.700    630.400  0.0804       0.1941
062897 11221    TUP 2015-09-30    36.200    124.700  0.2903       0.2335
006066 2787     IBM 2015-09-30  2950.000  13294.000  0.2219       0.2196
180402 15479   HSNI 2015-09-30    34.208    103.889  0.3293       0.1532
002285 639       BA 2015-09-30  1704.000   6740.000  0.2528       0.1432
187462 16035   UBNT 2015-09-30    53.759    413.733  0.1299       0.1433
003007 991      EAT 2015-09-30    33.207   -108.140 -0.3071       0.7062
011672 5955     TJX 2015-07-31   549.335   4276.067  0.1285       0.1322
012216 6147    LLTC 2015-06-30   132.715   1577.927  0.0841       0.1004
004462 1887     NEU 2015-09-30    62.009    376.181  0.1648       0.1289
010618 5203     TTC 2015-07-31    53.324    465.173  0.1146       0.1098
185881 15815    BAH 2015-09-30    56.216    268.984  0.2090       0.2612
060900 10757   DISH 2015-09-30   196.479   2855.912  0.0688       0.5394
010920 5427     UPS 2015-09-30  1257.000   1929.000  0.6516       0.2631
006774 3235     LMT 2015-06-30   929.000   2982.000  0.3115       1.7360
005252 2257     GGG 2015-09-30    50.691    636.492  0.0796       0.1043
005597 2467     HSY 2015-09-30   154.771    888.613  0.1742       0.1357
008247 4067     PPG 2015-09-30   433.000   5111.000  0.0847       0.1070
008543 4259      MO 2015-09-30  1528.000   2887.000  0.5293       0.3601
016101 7267    ABBV 2015-09-30  1239.000   4863.000  0.2548       0.2428
006304 2899    KLAC 2015-09-30   104.897    294.441  0.3563       0.1079
006733 3187      LB 2015-07-31   203.000   -648.000 -0.3133       2.2828
003170 1103      CL 2015-09-30   726.000    255.000  2.8471       0.6933
006435 3011     KMB 2015-09-30   517.000     54.000  9.5741       1.0709
180833 15543    MJN 2015-09-30   155.200    351.500  0.4415       1.2323
005680 2579      HD 2015-07-31  2234.000   8637.000  0.2587       0.1250
002663 799      CPB 2015-07-31    17.000   1380.000  0.0123       0.1146
009667 4755     SHW 2015-09-30   374.491    976.165  0.3836       0.1839
013092 6467    JACK 2015-09-30    23.141     15.953  1.4506       0.1985
065417 11829    YUM 2015-09-30   421.000   1825.000  0.2307       0.1390
003121 1071     CLX 2015-09-30   172.000    119.000  1.4454       1.2540
122380 12581    LII 2015-06-30    81.200     55.700  1.4578       0.5606
065772 11941    MTD 2015-09-30    88.861    586.352  0.1515       0.1050
160225 13685     MA 2015-09-30   977.000   6267.000  0.1559       0.1254

              ev_ebit  net_debt_ebit_ttm
gvkey
165652 14408     3.69               0.77
012785 6339      4.96               0.48
004990 2113      5.27               0.06
001045 15        5.36               1.54
010443 5059      6.70               1.97
170297 14504     6.84               0.64
009248 4595      6.85              -0.25
165675 14439     7.20               3.00
024856 9086      7.26               0.31
165675 14440     7.49               3.00
005234 2225      7.58               2.49
014311 6931      8.84               0.32
032280 10708     9.29               2.35
       10709     9.32               2.35
175263 14840     9.43               1.68
008606 4323      9.59               3.40
012589 6307      9.76               3.72
062897 11221     9.88               2.21
006066 2787     10.11               1.86
180402 15479    11.04               2.14
002285 639      11.87              -0.10
187462 16035    12.22              -1.76
003007 991      12.51               3.37
011672 5955     12.82              -0.17
012216 6147     13.15              -1.76
004462 1887     13.58               1.10
010618 5203     13.75               0.89
185881 15815    13.85               3.27
060900 10757    14.36               1.08
010920 5427     14.69               1.38
006774 3235     14.76               1.06
005252 2257     14.81               1.10
005597 2467     14.88               1.66
008247 4067     15.00               1.58
008543 4259     15.05               1.32
016101 7267     15.41               2.94
006304 2899     15.48               1.17
006733 3187     15.78               1.95
003170 1103     16.04               1.28
006435 3011     16.08               2.10
180833 15543    16.39               0.49
005680 2579     16.57               1.30
002663 799      16.75               3.20
009667 4755     17.06               1.22
013092 6467     17.26               3.50
065417 11829    17.35               1.21
003121 1071     17.46               1.77
122380 12581    19.24               2.93
065772 11941    19.73               1.01
160225 13685    19.79              -0.77